sudo: required

addons:
  apt:
    packages:
      - git
      - python-software-properties
#  hosts:
#    - boundless-test

services:
  - docker

language: python

python:
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - IMAGE=qgis/qgis
    - PLUGIN_NAME=oscertstore
    - PIP_EXECUTABLE=pip3
    - PYTHON_EXECUTABLE=python3
    - ON_TRAVIS=true
    - MUTE_LOGS=true
#    - secure: gxQrGNZOmBc6QujZCP6iO1AgOBP/DWXfUgYRzpQrlMPMlyDdMrjBo11UrRiqIhvsU0xTyA0LiOS4RQg1G9aWcftwtVzYw3luwLQqXatFe9TacA7IXVD2DMeekknSLBMi7d7769pCxT3sPEkAdypEvvmsrqVXx78cdEabL9Rvd7hphlbB1c34YboWl51P/6Lj4EFN3+n/sxRS5XaLKDK6PKQWpB/X0AprgtyWDJ7VOPmWyLFxyr96MDT5NHOAXL4g8O6MRa0EtggSqlVWce5ZF22tloz+8ovsQQwp76MsTQr+iSbXo/shHUqceArkHvJYwFL+rGvHyBaasy1J1tMow5EGcGxH80OyD+zFohqaBGm7o1WzgZnqKqph0+BXYggQm0H5ZkpTM0sWkB3MwkeV2Zi0Wiyotso2JL4JGd7WtN+Z/IeCbiva913yhWUFg9IFDgri+AICvPLx3JyYj3oBemakj5mveAm7dGklw/szoxE6Z3OKk+WHFppGJCqNCofguiQjVUxPa/P0oTAsGO2HUUPCTIXN2DX7vHs+yLzPMIpzriGlWCaGQCNpswRVNZOyZwj2Gw2aEZ1OcklITkeYG4koLowEVSSVvWCC3Ye5bMfuc4Og9VcxrU6QlETQYF2cD2vYuZdGHv4ZPt5dllz2LXGxEyS8/teYdGyITeBvbFs=
#    - secure: MYUfhTMN6Iy9m1zlKSfAfEaCMPCXolICfd79BHVfwnSq0rgraETEy1tJ+L71hVBzkDhVXF/jt7rIKcysKRLedvnFDeC25waqhAgKIXo6LzE6UKvvg0fw6bL+duA73GjR4aT+869Uam/g8Kit2dzBHpFDSDBVsy5WHwE2Q8sTQmync9sdTol+fvYHJ5shDxnsqb+zyEUNqqqeh1L26nFm5r0OZGKO5sX+gDvcA3UWNOeUMB7Bh+Aj2ZPoOWuo495VQ6fOIsqM9lBUph+zlhUYAVPBekl9V7kGMFlwOC/dLJHfumXZ4NLoSjbtUTlhAGcRSA0WeCUAvbdxpB26M/dsWBb//gcM62jsP8+PBe856GWSlB3fVvMBVe8MwVzVE492DwLH2/ePdowZJVu4MmItTuyLO1tlQl4ySFKoyCAQQ1btjM/UWllFIbeLEn2s6Y8S9WysiEUdY84+G8/xe+wSshGfNzhd2KgRzgoVkkTgUbNClpbNp+y8l3HasPK7OIfUpRPvhmELxDiSXOywujB/KCwRxtLrAMzW2vaMvN6Gz/W2iwlshONo8uIi/kWVs/atCC5UC95hAsAxbqpTt0g0eS0qjMbueLadB0muJHvY8ihH3nkeVn6Hp9M/pq9O0SWmfnDZpdA2eNhcXI/5J7Cky4rjcM6SLf3a7cOTiXJhS/U=

  matrix:
    - QGIS_VERSION_TAG=release-3_4

matrix:
  allow_failures:
    - env: QGIS_VERSION_TAG=release-3_4

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}
#  - docker tag ${IMAGE}:${QGIS_VERSION_TAG} qgis-testing-environment

install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e WITH_PYTHON_PEP=${WITH_PYTHON_PEP} -e ON_TRAVIS=${ON_TRAVIS} -e MUTE_LOGS=${MUTE_LOGS} -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
- sleep 10
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker exec -it qgis-testing-environment sh -c "$PIP_EXECUTABLE install paver"

script:
- docker exec -it qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
#- docker exec -it qgis-testing-environment sh -c "echo '${PLUGIN_NAME} has no unit tests yet, please create them and add here'"
- docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.testerplugin.run_tests"

#after_success:
#- |
#    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
#        mkdir /home/travis/.ssh/
#        chmod 700 /home/travis/.ssh/
#        openssl aes-256-cbc -K $encrypted_e0d17a9dded8_key -iv $encrypted_e0d17a9dded8_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
#        tar xzvf travis_secrets.tar.gz
#        mv id_rsa.qgisrepoguest /home/travis/.ssh/id_rsa.qgisrepoguest
#        mv ssh_config /home/travis/.ssh/config
#        chmod 600 /home/travis/.ssh/id_rsa.qgisrepoguest
#        chmod 600 /home/travis/.ssh/config
#        export RELEASE_ZIPNAME=${PLUGIN_NAME}.zip
#        echo "Uploading ${RELEASE_ZIPNAME} to QGIS Dev..."
#        scp ${PLUGIN_NAME}.zip qgisrepoguest:${UPLOADS}/${RELEASE_ZIPNAME}
#        export GIT_REV=$(git rev-parse --short HEAD)
#        ssh qgisrepoguest "${UPDATER} update --dev --role desktop-qgis-plugin-dev --git-hash ${GIT_REV} ${RELEASE_ZIPNAME}"
#    fi
